version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - cd client && npm install
  build:
    commands:
      - echo Building the Next.js app...
      - npm run build
  post_build:
    commands:
      - echo Packaging the app...
      - zip -r ../myapp.zip .next package.json public

artifacts:
  files:
    - myapp.zip
