version: "3.8"

services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # environment:
    #  - NODE_ENV=development
    restart: always
    volumes:
      - ./client:/app
      - ./client/node_modules:/app/node_modules

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
    restart: always
