version: "3.8"

services:
  gorilla-labs-client:
    container_name: gorilla-labs-client
    image: elarsaks/gorilla-labs-client:latest
    ports:
      - "3000:3000"
    environment:
      - NEXTAUTH_SECRET=${NEXT_PRODUCTION_SECRET}
      - NODE_ENV=production
    restart: always

  gorilla-labs-nginx:
    container_name: gorilla-labs-nginx
    image: elarsaks/gorilla-labs-nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - gorilla-labs-client
    restart: always
