name: Deploy Next to EC2

on:
  push:
    branches:
      - deploy-next

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # checkout the repository content to github runner.
      - name: Checkout
        uses: actions/checkout@v2

      # setup nodejs environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "18.16.1"

      # cache the dependencies to speed up the build
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ./client/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # install dependencies
      - name: Install dependencies
        working-directory: ./client
        run: npm install

      # build the next app
      - name: Build
        working-directory: ./client
        run: npm run build

      # Package the Next.js application for deployment
      - name: Package application
        working-directory: ./client
        run: |
          zip -r ../deploy.zip .next package.json next.config.js public

      # Deploy to EC2 instance using SSH
      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: "deploy.zip"
          target: "/path/to/deployment/directory"

      # Execute deployment script on EC2 instance (optional)
      - name: Execute deployment script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd /path/to/deployment/directory
            unzip deploy.zip
            # Add any additional commands needed for deployment, like restarting your Node application
