name: Build and Deploy Docker Image to EC2

on:
  push:
    branches:
      - deploy-next

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_REGISTRY_TOKEN }} | docker login -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t elarsaks/gorilla-labs-client:${{ github.sha }} ./client

      - name: Push Docker image to Docker Hub
        run: docker push elarsaks/gorilla-labs-client:${{ github.sha }}

  deploy-to-ec2:
    needs: build-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Docker Pull & Run From Hub
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          username: ubuntu
          script: |
            echo ${{ secrets.DOCKER_REGISTRY_TOKEN }} | docker login -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} --password-stdin
            docker pull elarsaks/gorilla-labs-client:${{ github.sha }}
            docker stop gorilla-labs-client || true
            docker rm gorilla-labs-client || true
            docker run -d --name gorilla-labs-client -p 80:80 elarsaks/gorilla-labs-client:${{ github.sha }}
