name: Build and Deploy Docker Image to EC2

on:
  push:
    branches:
      - deploy-next

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_REGISTRY_TOKEN }} | docker login -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t elarsaks/gorilla-labs-client:${{ github.sha }} ./client

      - name: Push Docker image to Docker Hub
        run: docker push elarsaks/gorilla-labs-client:${{ github.sha }}

  deploy-to-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Docker image to EC2
        run: |
          # SSH into the EC2 instance and pull/run the Docker image using the provided key
          ssh -o StrictHostKeyChecking=no -i <(echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}") ubuntu@${{ secrets.EC2_HOST }} <<EOF
            docker pull elarsaks/gorilla-labs-client:${{ github.sha }}
            docker run -d --name gorilla-labs-client -p 80:80 elarsaks/gorilla-labs-client:${{ github.sha }}
          EOF
