name: Deploy Next to EC2

on:
  push:
    branches:
      - deploy-next

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  package:
    runs-on: ubuntu-latest

    steps:
      - name: Package application
        working-directory: ${{ github.workspace }}/client
        run: |
          # Zip the project files
          zip -r ../deploy.zip .

  validate-ssh-access:
    runs-on: ubuntu-latest

    steps:
      - name: Validate SSH Access
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: echo "SSH Connection Successful"

  deploy-to-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: "deploy.zip"
          target: "/home/ubuntu/nextjs"

  execute-deployment-script:
    runs-on: ubuntu-latest

    steps:
      - name: Execute deployment script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            # Unzip the deployment package
            cd /home/ubuntu/nextjs
            unzip -o deploy.zip

            # Install dependencies
            npm install

            # Build the Next.js application
            npm run build

            # Use PM2 to start the application in production mode
            pm2 start npm --name "next-app" -- start

            # Save the PM2 process list and configuration
            # This ensures that PM2 can resurrect your process list on server reboots
            pm2 save

            # Optionally, set PM2 to automatically resurrect your applications on system startup
            pm2 startup
